import Button from "./Button";

export default function Keyboard({ currentTheme, mainCalculation }) {
  return (
    <div
      style={{ backgroundColor: currentTheme.keypadBg }}
      className="keyboard"
    >
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        7
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        8
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        9
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="delete"
      >
        DEL
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        4
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        5
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        6
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        +
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        1
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        2
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        3
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        -
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        .
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        0
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        /
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="number"
      >
        x
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="reset"
      >
        RESET
      </Button>
      <Button
        currentTheme={currentTheme}
        mainCalculation={mainCalculation}
        className="equal"
      >
        =
      </Button>
    </div>
  );
}
