import Button from "./Button";

export default function Keyboard({
  currentTheme,
  setOperation,
  setResult,
  operation,
}) {
  return (
    <div
      style={{ backgroundColor: currentTheme.keypadBg }}
      className="keyboard"
    >
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        7
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        8
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        9
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="delete"
      >
        DEL
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        4
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        5
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        6
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        +
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        1
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        2
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        3
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        -
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        .
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        0
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        /
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="number"
      >
        x
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="reset"
      >
        RESET
      </Button>
      <Button
        setOperation={setOperation}
        operation={operation}
        setResult={setResult}
        currentTheme={currentTheme}
        className="equal"
      >
        =
      </Button>
    </div>
  );
}
